
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 01 21:42:19 BRST 2012
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 36;
  public static final int LKEY = 23;
  public static final int GE = 15;
  public static final int UMINUS = 9;
  public static final int INTEGER = 2;
  public static final int LPAREN = 19;
  public static final int ARRAY = 39;
  public static final int FOR = 41;
  public static final int MINUS = 6;
  public static final int RPAREN = 20;
  public static final int SEMICOLON = 32;
  public static final int AND = 16;
  public static final int LT = 12;
  public static final int NIL = 38;
  public static final int TYPE = 37;
  public static final int IN = 29;
  public static final int OR = 17;
  public static final int COMMA = 33;
  public static final int DIV = 8;
  public static final int ENDFOR = 43;
  public static final int PLUS = 5;
  public static final int ASSIGN = 18;
  public static final int IF = 25;
  public static final int ENDWHILE = 46;
  public static final int DOT = 34;
  public static final int ID = 4;
  public static final int LE = 13;
  public static final int OF = 40;
  public static final int EOF = 0;
  public static final int RKEY = 24;
  public static final int error = 1;
  public static final int BREAK = 47;
  public static final int EQ = 10;
  public static final int LBRACK = 21;
  public static final int TIMES = 7;
  public static final int COLON = 31;
  public static final int ELSE = 27;
  public static final int RBRACK = 22;
  public static final int TO = 42;
  public static final int WHILE = 44;
  public static final int LET = 28;
  public static final int THEN = 26;
  public static final int NE = 11;
  public static final int END = 30;
  public static final int STRING = 3;
  public static final int GT = 14;
  public static final int VAR = 35;
  public static final int DO = 45;
}

